### ISSUE TITLE
Answers Won't Display on Back Side

### ISSUE THREAD

**Issue by johnprz93** [zjosua/anki-mc#10]
Sorry, just saw that you listed a issue tracker on the add-on page. I'll just copy and paste my original post here. I've attached screenshots to help navigate through the issue. Thanks again!

Super cool add-on! I know a lot of anki users think that MC is kind of a passive way to study but I find it challenging just to sit there and try to think up challenging questions (especially those tough all of the answers apply except or those multiple answer questions). Anyways, I'm looking forward to using this add-on but I had a problem displaying the answers. I'm using the AllInOne (kprim, mc, sc) note type and when I answer the question it only displays the question and the extra field. Any thoughts to why that might be happening? I'm on Anki Version 2.1.24 (359b9f5c). Thanks for all the great work!

![image](https://user-images.githubusercontent.com/64476439/80487820-07721880-8923-11ea-8acc-812de88b941e.png)
![image](https://user-images.githubusercontent.com/64476439/80487892-253f7d80-8923-11ea-878d-9ef95608f064.png)
![image](https://user-images.githubusercontent.com/64476439/80487932-34263000-8923-11ea-827d-0f3119ce804a.png)
![image](https://user-images.githubusercontent.com/64476439/80488056-66379200-8923-11ea-8592-77aa8d9180cd.png)

**Comment by zjosua** [comment]
I can't reproduce this, which makes it hard to find the problem.
Could you please export this note and upload the .apkg file here?

**Comment by johnprz93** [comment]
Here you go!

**Comment by zjosua** [comment]
I can't see the file, probably because you commented via email reply.
Looks like you need to open [https://github.com/zjosua/anki-mc/issues/10](https://github.com/zjosua/anki-mc/issues/10) in your browser an log in to your github account.

**Comment by johnprz93** [comment]
How about that?

[MC Question.apkg.zip](https://github.com/zjosua/anki-mc/files/4548113/MC.Question.apkg.zip)

**Comment by zjosua** [comment]
Yes, I've got the file now, but your note works just fine for me.
Here is what I can think of:
- Is the screenshot from the reviewer or from the previewer?
- Which OS are you using?

**Comment by johnprz93** [comment]
Weird! Well the screenshot was from the previewer but I got the same result from the reviewer. And I'm currently on Mac version 10.15.3. It looks like I'm quite behind on updates for the mac so maybe that might be it?

**Comment by zjosua** [comment]
I've tried on my old MacBook as well and it's working there as well.
However, I run the alternate version of Anki on that MacBook, because it only supports OS X 10.11.
I'm guessing you use Anki's standard version?

The add-on does not work in the previewer for some reason, but I currently don't want to work on that.

**Comment by johnprz93** [comment]
Hey, good news! Updating the mac seemed to do the trick so sorry about the hassle but at least now we know if anyone comes asking again. Appreciate the work you do. Thanks again.

John P.

**Comment by zjosua** [comment]
Ok, good to know.

**Comment by marguerita246** [comment]
how can i use answers what 00010 mean

**Comment by marguerita246** [comment]
can you put a vid on youtube how to use it

**Comment by zjosua** [comment]
"0 0 0 1 0" in the "Answers" field means that Q_1, Q_2, Q_3 and Q_5 are incorrect, and Q_4 is correct.
Keep in mind that the digits in the "Answers" field have to be separated by a single space.

**Comment by marguerita246** [comment]
Thanks a lot
