### ISSUE TITLE
Multiple Choice - Awnsers not rated

### ISSUE THREAD

**Issue by EmanuelSchirm** [zjosua/anki-mc#105]
I have the repeated problem that one awnser will not be corrected/rated at all in multiple choice with 4 different answers. 
For example:
Question: 
1
1
1
1
Awnser: 
1
1
1
1
Result:
1 (Green)
1 (Green)
- (White)
1 (Green) 
![image](https://user-images.githubusercontent.com/104327020/218577219-a6449335-bbaf-4a5b-b8c9-35c99ff83ce2.png)
![image](https://user-images.githubusercontent.com/104327020/218577307-88e60ff6-c78f-4eaa-a188-0d318404a4ff.png)

**Comment by 3ter** [comment]
I can offer you to check your note. Export it from anki (use the defaults) and zip it to append it to a message in this issue.

**Comment by 3ter** [comment]
No answer from issue author.
