### ISSUE TITLE
Wrong answers  on multiple choice

### ISSUE THREAD

**Issue by lanox** [zjosua/anki-mc#108]
Hi

I am just wondering if this plugin is still supported.

I seem to be getting wrong answers , see the images below.
<img width="767" alt="Screenshot 2023-07-09 at 6 04 15 pm" src="https://github.com/zjosua/anki-mc/assets/7599183/b3758118-0522-4ad5-a578-076703c21994">
<img width="1140" alt="Screenshot 2023-07-09 at 6 04 59 pm" src="https://github.com/zjosua/anki-mc/assets/7599183/426b5172-fa59-45fa-b2d7-e30495c58496">

Not sure If I am doing anything wrong?

Thanks

**Comment by 3ter** [comment]
I wouldn't say it's in active development (as in getting new features regularly) but it's in use and if there's an issue it is going to be addressed.

Please export your (testing) note so I can check if it's something with your environment or not (use the default settings and zip it to attach it to your answer).

**Comment by lpuljic** [comment]
> I wouldn't say it's in active development (as in getting new features regularly) but it's in use and if there's an issue it is going to be addressed.
> 
> Please export your (testing) note so I can check if it's something with your environment or not (use the default settings and zip it to attach it to your answer).

Thanks, I think I figured it out, I didn’t have a space in between the numbers for answers, but once I added the space, it seems to be working fine.

thanks, it’s a great plug-in.

**Comment by lanox** [comment]
> I wouldn't say it's in active development (as in getting new features regularly) but it's in use and if there's an issue it is going to be addressed.
> 
> Please export your (testing) note so I can check if it's something with your environment or not (use the default settings and zip it to attach it to your answer).

Thanks, I think I figured it out, I didn’t have a space in between the numbers for answers, but once I added the space, it seems to be working fine.

thanks, it’s a great plug-in.

**Comment by lanox** [comment]
update, one thing I have noticed is that Q_6  is not been displayed at all.

**Comment by FelipeTesta** [comment]
Just installed the add-on and got the same problem on single choice.

![BUG 10072023_Single Choice Color](https://github.com/zjosua/anki-mc/assets/24526967/dbed7177-0232-40f3-a1f2-9ccc94c73106)

It seems like there's a disconection between the background color with the actual right answer in the back-card script, but apparently only when the answer is wrong.

This functionality is really awesome, if somebody could solve this it help a lot.

**Comment by 3ter** [comment]
That's actually not a bug, but a potential feature. Currently you have to manually edit your note type:
- Just add your additional question fields to the list
```
<div class="hidden" id="Q_1">{{Q_1}}</div>
<div class="hidden" id="Q_2">{{Q_2}}</div>
<div class="hidden" id="Q_3">{{Q_3}}</div>
<div class="hidden" id="Q_4">{{Q_4}}</div>
<div class="hidden" id="Q_5">{{Q_5}}</div>
```
- In your case add
```
<div class="hidden" id="Q_6">{{Q_6}}</div>
```

**Comment by lanox** [comment]
Thank you .
