### ISSUE TITLE
The colors for right/wrong answers are reversed

### ISSUE THREAD

**Issue by learnwell** [zjosua/anki-mc#11]
I'm using Anki Version 2.1.23 (de9543ff)

The colors for right and wrong answers seem to be reversed on mobile. I think its because a tap on mobile is like "show answer" so it never gets a chance to grab the touch input for the checkbox or radio bullet. Then probably it thinks the questions was never answered.

Snapshot from iPhone shows the issue:
<img width="524" alt="Screen Shot 2020-05-11 at 12 34 57 PM" src="https://user-images.githubusercontent.com/29492715/81603950-0362e380-9384-11ea-9564-7668d1325d80.png">

Just to make sure that this is not a configuration issue on my side rather than an actual bug, I'm including the card source and resulting snapshot.

[test1.txt](https://github.com/zjosua/anki-mc/files/4611669/test1.txt)
<img width="436" alt="Screen Shot 2020-05-11 at 12 31 47 PM" src="https://user-images.githubusercontent.com/29492715/81603555-63a55580-9383-11ea-9f65-074c84619fe4.png">

Snapshot from laptop shows that everything works:
<img width="435" alt="Screen Shot 2020-05-11 at 12 35 53 PM" src="https://user-images.githubusercontent.com/29492715/81603936-fe059900-9383-11ea-82ac-c30053af71d7.png">

**Comment by learnwell** [comment]
The simplest workaround I could think of (iOS/iPhone-wise) would be to simply **not** show the part of the table that repeats what the user might have selected as the right answer ... i think I and hopefully other iOS mobile users could get by on just that much :)

**Comment by zjosua** [comment]
That is intended behaviour. The colors do not represent the correct answer(s), but indicate whether you answered correctly or not.
In this example, "zwitterion" is orange, because as the correct answer you should have ticked it, but you did not. All the other options are incorrect and you correctly rated them as such by not ticking them. Therefore, they are highlighted green.

**Comment by learnwell** [comment]
Yes but I cannot tick them on iphone. It accepts a tap as an answer itself.

If that makes sense, what do you think about this suggestion for iOS/mobile users?
> Don't show the part of the table that repeats what the user might have selected as the right answer.

As that's not important, I can just think to myself the answer is A and then i tap and then if its not then I know right away anyway.

Not sure if you have info in your JS to figure what platform its running on.

**Comment by zjosua** [comment]
Hm, I think I've heard of the Anki mobile tap to show answer "feature" before.
Isn't there an option to disable this? I can't test it myself, because I don't have an iOS device.

**Comment by Schlauer-Hax** [comment]
I see the Problem. 

IOS seems to not passthrough the touches to the card. 
In the settings you can set actions when you tap but its not possible to pass through the tap to the card. 
I also tested it with other types of cards but that also didn't work, so the app is the problem which is something we can't change.

**Comment by itorgon** [comment]
I'm having same thing in iOS devices, both, iPhone n iPad. In my laptop works perfect, I love it, but whenever I want to do a review out of my laptop this thing happens. 
And its weird, cause it says that thing of:
" Correct answers: 75 % "
Which I don't understand hehehe


![image](https://user-images.githubusercontent.com/78241231/107865701-ad1e5600-6e69-11eb-8421-c4973504fb67.png)

**Comment by 3ter** [comment]
@zjosua Can you please close all but one issues regarding this very same issue on iOS? I think it would make it easier for new users to find the workaround
