### ISSUE TITLE
Error when opening Anki App

### ISSUE THREAD

**Issue by Shahin-rmz** [zjosua/anki-mc#110]
#### Describe the bug
*A clear and concise description of what the bug is.*
This is actually not a bug, but whenever I open the anki, I get some error messages related to this addon.

*If Anki shows an error message, copy and paste it between the backticks below.*
```python

```

#### To Reproduce
1. just open the Anki app. the error will be shown.

#### Expected behavior
*A clear and concise description of what you expected to happen.*
No error
#### What have you tried?
*Before we suggest or explore something you've already discovered to not work, tell us what you have already tried to fix the problem.*
- 

#### Screenshots
*If applicable, add screenshots to help explain your problem.*

#### Information about your set-up
[anki_log.txt](https://github.com/zjosua/anki-mc/files/12067623/anki_log.txt)

On which platform(s) does the error occur?
- [ ] Ankiweb
- [x] Desktop: *type your OS including version here*
- [ ] Mobile: *type your OS including version here*

*Only if the error occurs with the Anki desktop app:*
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*

* I will attach the error log as .txt file *.
[anki_log.txt](https://github.com/zjosua/anki-mc/files/12067629/anki_log.txt)

#### Additional context
*Add any other context about the problem here.*
First of all thanks for developing the addon.
I have not faced any issues, but just see an error.
wanted to inform you so it does not make any further problems.
Best

**Comment by 3ter** [comment]
Thanks for the report, I'm going to look into it - and especially why it didn't occur in my testing. Infinite recursion wasn't the intention, naturally.

**Comment by Shahin-rmz** [comment]
Thanks for follow up.
It is already mentioned in log, but for the record, I am using Ubuntu 22.04 platform.
If there are any other questions, I'll be happy to help.

**Comment by bwilder** [comment]
I'm also getting this message

**Comment by turtlecoder** [comment]
Just installed and faced the same issue. No regressions noticed so far.
