### ISSUE TITLE
Fehler beim Installieren

### ISSUE THREAD

**Issue by LK2408** [zjosua/anki-mc#117]
*If you're about to tell me that the answer coloring is incorrect, kindly stick
it and create a pull request that adds the option to switch to your preferred
color coding instead. The current color coding is exactly how I want it to be.
Just because I share my code doesn't mean that I provide a service to adapt it
to everyone's and their mom's wishes.*

#### Describe the bug
*A clear and concise description of what the bug is.*
Installed the add-on, restarted Anki so the add-on gets applied and the error message below popped up
*If Anki shows an error message, copy and paste it between the backticks below.*
```python
Eine der installierten Erweiterungen konnte nicht geladen werden. Wenn das Problem weiter besteht, bitte über den Menüpunkt Extras → Erweiterungen die Erweiterungen deaktivieren oder deinstallieren

Beim Laden von '⁨Multiple Choice for Anki⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/lennartknigge/Library/Application Support/Anki2/addons21/1566095810/__init__.py", line 37, in <module>
    from aqt.gui_hooks import addon_config_editor_will_update_json, profile_did_open
ImportError: cannot import name 'addon_config_editor_will_update_json' from 'aqt.gui_hooks' (unknown location)
```

#### To Reproduce
1. Copy Paste Code from add-on website into add-on section in Anki
2. restart anki

#### Expected behavior
Thought it would normally work like the other add-ons I have installed

#### What have you tried?
Uninstall and reinstall
- 

#### Screenshots
*
<img width="412" alt="Bildschirmfoto 2023-11-11 um 06 52 13" src="https://github.com/zjosua/anki-mc/assets/150504844/c94ef337-8bba-4f5f-8edf-e7509b5f8fef">

.*

#### Information about your set-up

On which platform(s) does the error occur?
- [ ] Ankiweb
- [ ] Desktop: *macOS 14.0 (23A344)*
- [ ] Mobile: *type your OS including version here*

*Only if the error occurs with the Anki desktop app:*
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 14.0
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-11-10 09:25:22
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2023-06-18T13:37, 'None', '']
    Advanced Browser ['874215009', 2023-07-01T21:55, 'None', '']
    Hint Hotkeys ['1844908621', 2023-04-14T16:13, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2022-04-09T09:15, 'None', '']
    Mini Format Pack ['295889520', 2023-11-02T19:00, 'None', '']
    Multiple Choice for Anki ['1566095810', 2023-07-20T11:59, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T16:14, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
    True Retention ['613684242', 2017-11-19T21:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1237621971 1374772155 1566095810 1642550423 1771074083 1844908621 295889520 613684242 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Additional context
*Add any other context about the problem here.*

**Comment by zjosua** [comment]
Thanks for the report. I forgot to update the compat section of the README.
You need Anki 2.1.55 or higher for the most recent version of the add-on.
For Anki 2.1.44 to 2.1.54 you can use [v2.8.0 ](https://github.com/zjosua/anki-mc/releases/download/v2.8.0/anki-mc-v2.8.0-qt5+qt6.ankiaddon) (or older) of the add-on.
