### ISSUE TITLE
Displaying wrong answer

### ISSUE THREAD

**Issue by praticallyadoctor** [zjosua/anki-mc#12]
The answer showing up in the final card is not the answer entered during setup.  Example given below, but this is happening for multiple cards, not just this one. 

Setup: 
![anki 1](https://user-images.githubusercontent.com/65972171/82930702-d00f7f80-9f53-11ea-8320-c23b48fd09ad.png)

Display: 
![anki 2](https://user-images.githubusercontent.com/65972171/82930824-fcc39700-9f53-11ea-8ca5-f2a1ef8ad123.png)

**Comment by zjosua** [comment]
The ones and zeroes in the "Answers" field have to be separated by a single space.

**Comment by praticallyadoctor** [comment]
Thank you! It must be a fluke that some are displaying correctly.

**Comment by zjosua** [comment]
In the above example "0010" is used as the Answer for Q_1, and since it is not zero, this is considered a correct answer.
I guess that the notes that were displayed correctly all had only Q_1 as a correct answer.
