### ISSUE TITLE
Not showing all Q and fields.

### ISSUE THREAD

**Issue by c0c0loco** [zjosua/anki-mc#122]
I've been working with this addon the whole day and I noticed 2 issues:

So, if I type 4Q but it shows only 3 in some cases? Idk why.
Screenshot with the addon working as intended:
![image](https://github.com/zjosua/anki-mc/assets/149329867/9cbb8019-cfa5-4ceb-8eef-5b0997c92a55)
Screenshot with the addon not working as intended:
![image](https://github.com/zjosua/anki-mc/assets/149329867/59572468-41b5-4d52-8fa8-3e414c2b00fd)

Also, I switched the name of one field and it's not working anymore (not showing after answering the flashcard). I use it for explanations of the cards. It was working a while ago but I decided to check it and noticed it's not working anymore?
Fields:
![image](https://github.com/zjosua/anki-mc/assets/149329867/d985268b-5a44-47c9-bdd4-16e08b53a553)
Screenshot with my 2 issues (showing 3Q instead of 4 and the fields's problem) I had to use the field 'Sources' instead as you can see:
![image](https://github.com/zjosua/anki-mc/assets/149329867/a8289a5c-845f-442d-9113-1c9161985b70)

On which platform(s) does the error occur?
- [ ] Ankiweb
- [X] Desktop: 
- [ ] Mobile: 

Debug Info
```

```

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Japanese ['1344485230', 2023-12-19T05:02, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T16:34, 'None', '']
AnkiConnect ['2055492159', 2024-01-02T03:16, 'None', mod]
Button Colours Good Again ['2494384865', 2022-09-27T12:18, 'None', '']
CSS Injector - Change default editor styles ['181103283', 2023-02-21T22:15, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T03:19, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T08:19, '6.18', mod]
Japanese Pitch Accent ['148002038', 2023-05-07T15:01, 'None', '']
Multiple Choice for Anki ['1566095810', 2023-11-17T21:59, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1210908941 1344485230 148002038 1566095810 1771074083 181103283 2055492159 2494384865 385888438 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by bralandealmeida** [comment]
For me, no option appears in the latest version of Anki

![Screenshot 2024-01-13 at 12 51 12](https://github.com/zjosua/anki-mc/assets/47180618/589b1c33-3045-4dd9-b626-c1a0ee7ace8c)
![Screenshot 2024-01-13 at 12 50 51](https://github.com/zjosua/anki-mc/assets/47180618/10d3aca9-c571-4123-bd1f-6994efe525b1)

**Comment by c0c0loco** [comment]
That's because you didn't set the answers (ex. 0 1 0 0 )

**Comment by bralandealmeida** [comment]
> That's because you didn't set the answers (ex. 0 1 0 0 )

Oh, thanks!
