### ISSUE TITLE
Frontcard is blank

### ISSUE THREAD

**Issue by RamonAgonalia** [zjosua/anki-mc#123]
Multiple Choice for Anki

It doesn't work in version 23.12.1. Notes are still right but, when the cards are opened to study, appears the message "The front of this card is blank". I tried to fix this problem but I can't. I don't know how to release my several hundreds of Allinone notes. :(

1. I open the deck
2. I click in "Study now"
3. A card is opened with text "Yes-No" and "The front of this card is blank"

#### Expected behavior
In previous versions, a card with multiple choice was run

#### Screenshots
![image](https://github.com/zjosua/anki-mc/assets/157009803/77f3c78d-bbed-4831-8c48-2b6bbc71e2a8)

#### Information about your set-up

On which platform(s) does the error occur?
- [x] Ankiweb
- [x] Desktop: Windows 10 22H2

*Only if the error occurs with the Anki desktop app:*
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*

It is not a bug, actually

**Comment by 3ter** [comment]
I don't really understand what's going on here as you write
> It is not a bug, actually
and then assign the `bug` label 😕 ?

I can offer you to check a note if you export it (use the default format) and attach it here. I haven't had much testing going on with the KPrim type (yes-no-question as above).

**Comment by RamonAgonalia** [comment]
> I don't really understand what's going on here as you write
> 
> > It is not a bug, actually
> > and then assign the `bug` label 😕 ?
> 
> I can offer you to check a note if you export it (use the default format) and attach it here. I haven't had much testing going on with the KPrim type (yes-no-question as above).

Sorry for the wrong 'bug' label assignment, and thanks for your reply, but I have already fixed the issue.

**Comment by 3ter** [comment]
Feel free to share your solution if others encounter the same problem and thank you for your swift response 😃 .

**Comment by Nameer6g6** [comment]
Can you explain how did you fix it?
I'm facing the same issue
