### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by a-starry-night** [zjosua/anki-mc#125]
Hi, I'm kind of new to Anki templates and wondered if it is normal that custom card templates don't support Mathjax. I just used it as I would normally and it seems to get ignored but i also don't know how to fix that myself - otherwise i would have done so.
Would be nice if anyone could explain that to me since i can't really find anything on that.
An example would be me trying to write M<sub>2</sub> like this \\(M_2\\) and the Preview then displaying it as is like here:
![grafik](https://github.com/zjosua/anki-mc/assets/130813679/64ad0953-d29c-4496-9cd9-9e644efdeb2d)
kind regards

**Comment by 3ter** [comment]
There should be no restrictions. Formulae are replaced while editing. If that's not the case for you it could be that another addon is interfering.
![image](https://github.com/zjosua/anki-mc/assets/11499929/9679f34d-5aad-4500-bfa4-7b848489ddb4)
![image](https://github.com/zjosua/anki-mc/assets/11499929/050490b9-5115-44c8-95e9-2662e21c6f12)

**Comment by a-starry-night** [comment]
Thanks for your quick reply :D
I deleted the plugin that this repo is based on (which I had already deactived so idk if that could've still be influencing the Mathjax-generation), restarted anki, tried to recreate your integral and now it somehow started working! I really don't know what the problem was but it's gone so thanks a lot!

**Comment by 3ter** [comment]
That's good to hear, I'm closing the issue.

As a side note: This addon "only" adds a template (or updates an existing one). So there is no actual function beside that so there should be no need to deactivate it or else.
