### ISSUE TITLE
Colors on single choice questions

### ISSUE THREAD

**Issue by ironhak** [zjosua/anki-mc#13]
Hi, I saw another one member had this issue but I'm not able to remove the colored part. This mess me up because I instinctively watch the green mark and I think that's the right one... but it's not. 

Here's an example: 
![Schermata 2020-06-05 alle 11 17 47](https://user-images.githubusercontent.com/62611612/83859415-30ee4300-a71e-11ea-9919-5e885e961e0a.png)
Why the second answer is marked green if the right one is the third?

**Comment by zjosua** [comment]
The colors don't show which answer is correct.
They show whether you selected correctly or not.

**Comment by wcoburn** [comment]
I'm having the same issue with the colors in the 'sc' mode. When the answer is correct things show correctly, but the reds and greens are seemingly random when the answer is wrong.

**Comment by Schlauer-Hax** [comment]
The colors on the screenshot are actually correct: 

- The first one is red because you choose it, which is wrong. 
- The second one is green because you didn't choose it, which is correct. 
- The third one is red because you didn't choose it, which is wrong

**Comment by 3ter** [comment]
This issue can be closed as the (very short) usage guide contains exactly this information
>The add-on will automatically style your choices based on whether you answered correctly or not.
