### ISSUE TITLE
Cannot get Answer to Display Correct or Incorrect

### ISSUE THREAD

**Issue by katiehamel** [zjosua/anki-mc#16]
![image](https://user-images.githubusercontent.com/71980374/94369876-4cf56600-00ba-11eb-8032-f50ef1199b75.png)
It will only say **Correct Answers: x %**, but not giving what percent or what answers are correct. I'm not sure if I have it formatted correctly. I attached a picture for the card creation in case that helps. 
![image](https://user-images.githubusercontent.com/71980374/94369988-00f6f100-00bb-11eb-89f6-aa654b0e227f.png)

**Comment by yeetblck** [comment]
I have the same problem. Did u fix it ?

**Comment by katiehamel** [comment]
Not legitimately, but I just put the correct answer in the Extra 1 field so
I could see if my guess was correct and it worked enough for my uses.

**Comment by zjosua** [comment]
@katiehamel what OS do you use? Have you tried on another device or on AnkiWeb?
I think that on some systems the JS might not get executed. But that's just about impossible for me to confirm or fix.
I'm not sure about it though.

**Comment by rdvrd** [comment]
I have same issue using windows and it acts the same on ankidroid too

**Comment by zjosua** [comment]
@rdvrd We broke some stuff with an update about two weeks ago.
Saturday's update should have fixed it. Could you try again with the newest version of the add-on?

**Comment by Leojoc** [comment]
I have the same issue. I using windows with ⁨2.1.42 (8eebfe18)⁩ anki version and Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Comment by Nailuj1** [comment]
I saw that you need to put 5 options ins the Answer field to get a right percentage and colors. Even if you don't have 5 Answers.

So instead of 0 0 0 1 you have to put 0 0 0 1 0.

**Comment by 3ter** [comment]
Resolved by latest updates.
