### ISSUE TITLE
Can you make it so that the answers are RANDOMized?

### ISSUE THREAD

**Issue by DoctorToBeIn23** [zjosua/anki-mc#17]
Its too easy to memorize the position on MC questions?

**Comment by zjosua** [comment]
The script does randomize the options.
Maybe your system does not allow all the required JS functions.
Which OS, Anki and device are you using?

**Comment by DoctorToBeIn23** [comment]
2.1.30 on Mac OS

**Comment by zjosua** [comment]
Can anyone recreate this? I can't diagnose the problem without being able to reproduce it.
@DoctorToBeIn23 Is it still not working with the most recent versions of Anki and the add-on?

**Comment by 3ter** [comment]
Couldn't reproduce.
