### ISSUE TITLE
Showing more than 5 choices

### ISSUE THREAD

**Issue by ysalam** [zjosua/anki-mc#18]
Is there a way to make it so that I can see more than five answers to choose from?
I added the fields via the Fields --> Add option
![image](https://user-images.githubusercontent.com/66516214/97405080-2c623b00-1908-11eb-9b60-6a7c9f4f66e4.png)

But for some reason any options I include after Q_5 just dont show up when im using the card. 

Love the add on
Thank you

**Comment by Schlauer-Hax** [comment]
That's right, because the code in the backend doesn't expect to have more than 5 answers but, it's possible to implement it i think.

**Comment by ysalam** [comment]
> That's right, because the code in the backend doesn't expect to have more than 5 answers but, it's possible to implement it i think.

Any idea how?

**Comment by Schlauer-Hax** [comment]
Sure, i submitted a pull request #20
