### ISSUE TITLE
Answer are not shown up in review

### ISSUE THREAD

**Issue by TrunkneFlut** [zjosua/anki-mc#24]
In editing, everything is normal. But if I review the card, no options/answers show up (see picture below). Friend of mine checked my card and it worked, so there must be some add-on issue. Do you know about add-ons causing this problem?

![image](https://user-images.githubusercontent.com/74065223/102883329-85f26c00-4458-11eb-955c-2d408771feb3.png)

**Comment by romerj0000** [comment]
Hello, I actually have the same exact problem, too. I realized I wasn't given any options/choices to choose from when reviewing my cards. It would also show up like that that this user has screentshotted. My anki is currently on the newest version, 2.1.37. I also logged in via ankiweb.com and it seems to work just fine through the actual website. Just not in the downloaded version. I really enjoy this add-on and it's worked perfectly fine before updating to the newest version. Please let us know if there is something we can do. Thank you!

**Comment by Bambuspony** [comment]
only at first card per session or at all cards? Here it is only at the first card per session.

**Comment by TrunkneFlut** [comment]
I have it with every card with this card type

**Comment by nukamax** [comment]
Just installed the add-on and I'm having the same issue. I really don't have time to play around with the code so my workaround has just been putting the answers in the little extras line, but if there's ever a fix for this that'd be great.

**Comment by johanndev** [comment]
I have the same problem.
Card editing view:
![image](https://user-images.githubusercontent.com/10048453/103154278-beff4900-4796-11eb-8ea1-3c7be41874e3.png)

Review:
![image](https://user-images.githubusercontent.com/10048453/103154289-d0e0ec00-4796-11eb-8d75-4f60f7218975.png)

**Comment by paulymundo** [comment]
I have the EXACT same problem, in every way, as JohannDev. He has documented it perfectly. Everything he displayed is happening to me. Truly frustrating. I am using Anki 2.1.38. I really don't want to reload an older version of Anki so I guess I'm going to wait to see what fixes arrive whenever. I am wondering if ther is a conflict with other addons. 

I am using the following addons: Button colours good again, Correct answers graph, Custom background image and gear icon, Image occlusion enhanced for Anki 21 Alpha, and Review heatmap.

 Looking forward to this working, It would be a big help.

Thank you.

**Comment by philippGitHub16** [comment]
Yeah I recognized the same problem after installing but I made kind of a funny discovery. The bug only occurs within the last card I create regardless of chosen type of question or using all Question blanks. So as soon as I add another card the previous "rotten" card works but the new one doesn't.

**Comment by 3ter** [comment]
In the **previous stable release 2.1.35** I can confirm that the scripts are executed also when the card is looked at for the first time (and not when switching between notes or doing other funny business like e.g. changing the card template code when managing the note type).

Downgrading is really easy so I recommend to follow the (two-step instructions) on the [anki ](https://apps.ankiweb.net/)page.

I suppose it would also make sense to open up an issue in the [main anki repo](https://github.com/ankitects/anki/issues) to get clear on why these scripts aren't called any longer when the card is encountered for the first time.

**Comment by 3ter** [comment]
I think I've got an (easy enough) fix together:
- Manage Note Types...
- Cards...
- Add the following state `interactive` to the `if` clause at the very end of the `<script>` tags on the Front Template
```js
if (document.readyState === "complete" || document.readyState === "interactive") {
```

For me this made it visible at all times so far.

**Comment by 3ter** [comment]
To make sure everything has actually been loaded (for some persistence I do not yet understand) I think it would be best to wait, e.g. replace the bottom section with this
```js
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function waitForReadyStateAndRun() {
    for (let i = 0; i < 100; i++) {
        if (document.readyState === "complete") {
            setTimeout(generateTable(), 1);
            break;
        }
        await sleep(100);
    }
}

if (document.readyState === "complete") {
    setTimeout(generateTable(), 1);
} else {
    waitForReadyStateAndRun();
}
```
