### ISSUE TITLE
adding more choices than 5

### ISSUE THREAD

**Issue by KrisRog** [zjosua/anki-mc#26]
Hi,
I'd like to add another 10 choices to my questions. How to edit the code of your add on to add 10 fields more?

**Comment by curious58** [comment]
Try going to ‘Manage Note Types’ in the tools option, choose the note type name and click ‘Add’ (i.e. make a copy of the original note type and rename it however you want). Go to field and add fields with the name format ‘Q_#’ (e.g. Q_6) then reposition the cards

Next, go to ‘Cards’ option and edit the part under the script for the Front template where it says 
“for (var 1 = 0; i < 5; i++) {“

Change 5 to the number of choices you want. (e.g. i < 10)

Next, go to the very bottom of the code (i.e. the one where you can see ‘<div class = “hidden” id = “Q_1”>{{Q_1}}</div>)

^ Just follow the above format for the code and change the numbers to 6,7,8,9,10 and so on, using 1 line per code. So for 2 additional fields with the name ‘Q_6’ and ‘Q_7’, 

Add the following after/below the Q5 line

<div class = “hidden” id = “Q_6”>{{Q_6}}</div>
<div class = “hidden” id = “Q_7”>{{Q_7}}</div>



Hope it works for you!
