### ISSUE TITLE
Shortcuts for reviews

### ISSUE THREAD

**Issue by itorgon** [zjosua/anki-mc#28]
Hi there! 
First of all, thanks for your work.
I'm using the add for a single choice from 4 quiz and,
I have a question... 
is there any option to use keyboard shortcuts to answer on the reviews? Like numbers or commands to choose whatever Q you want?
I would love to do that to go faster on the reviews... 
thanks in advance!

**Comment by 3ter** [comment]
Hi @itorgon,
would it be fast enough if you had to use <kbd>Alt</kbd> + the number keys?

Currently everything this addon provides comes from the javascript on the HTML template so we can't keep anki from capturing the number keys without modifying them with <kbd>Alt</kbd>.
Of course this can be changed, but it seems like a bit more of an effort to me.

For the "worked around" method I should have a PR ready for triage by the maintainers.

**Comment by itorgon** [comment]
Yeah, that would work super!
 ❤️

Dude, I realized Why in iOs shows that thing of 75% answers ok. It's like it dismiss the choice you make right after you click on it... 

Regards! 

Thanks a lot for your work!
