### ISSUE TITLE
Error showing answer.

### ISSUE THREAD

**Issue by huandney** [zjosua/anki-mc#31]
After this last update, the percentage and the result of the response are always shown as wrong.
Update:
I realized that this error happens when we use the mouse to choose the answer. When we use the shortcut it works well.

![error](https://user-images.githubusercontent.com/19948348/109401877-bad2e180-7927-11eb-80bf-7abdf7c94592.PNG)
![error2](https://user-images.githubusercontent.com/19948348/109401879-bc040e80-7927-11eb-8916-51438c4df3fa.PNG)

**Comment by 3ter** [comment]
Thanks a lot for pointing that out. That error is on me I suppose :blush: . I'm going to look into it.
