### ISSUE TITLE
Cards don't initialize correctly

### ISSUE THREAD

**Issue by zjosua** [zjosua/anki-mc#32]
![image](https://user-images.githubusercontent.com/5960563/109551639-168c9e80-7ad1-11eb-8cdb-4860e6b6cfa9.png)
Cards initially don't display the choices.
![image](https://user-images.githubusercontent.com/5960563/109551993-8c910580-7ad1-11eb-9f80-62cc66b12eb1.png)
After opening the card in the editor and closing the editor again, the cards are displayed correctly. Also, the first card after clicking "Study Now" is displayed correctly.

Seems like they are initialized correctly after a reload of the Reviewer, but not after answering the previous card.

**Comment by 3ter** [comment]
I can confirm this. You can also click on `Again` after answering when in study mode to make this issue show itself.

**Comment by 3ter** [comment]
After updating anki to 2.1.41 I'm having exactly the same behaviour as @zjosua described. Before (2.1.37 or 2.1.38) those cards initialized as expected.

**Comment by Ratonu13** [comment]
updated to v2.4.0, I have the same issue, but pressing edit still doesn't load the card. I can load the other cards after that if I click show answer for the first (it shows a blank card), then it works smoothly. It ruins the scheduling for that first card, unfortunately.
