### ISSUE TITLE
Anki Mobile iOS MC - right answer is wrong

### ISSUE THREAD

**Issue by rcanela1** [zjosua/anki-mc#35]
First thank you for the amazing add on, it works great on windows and max however on iOS every time I enter the right answer, it is wrong and all the other answers are right.

![A2C1733B-76C2-41DA-A1A8-62B254D96225](https://user-images.githubusercontent.com/28790598/109926970-cf451000-7c80-11eb-8c5e-78e24979430d.png)

**Comment by 3ter** [comment]
Hi there, nice to hear that you like the app in general.

Please have a look at the other issues where you can find a workaround:
https://github.com/zjosua/anki-mc/issues/14

**Comment by rcanela1** [comment]
Thank you so much for the quick feedback.
