### ISSUE TITLE
Error - "Correct answers: x %" on Windows 10 64 bit

### ISSUE THREAD

**Issue by KajikiaAudax** [zjosua/anki-mc#40]
No matter which answer I choose all it says on the back of the card is "Correct answers: x %"

This is happening to me with the brand new Anki update (2.1.42) on Windows 10 64 bit.

Best regards.

**Comment by 3ter** [comment]
Thanks for sending in your observation. Can you check the version of the addon to make sure the card template is up to date?
Tools - Addons - (select "Multiple Choice for Anki") - View Files - (open "manifest.json" and look at the version)
```
"version": "v2.3.2"
```
@zjosua Could it be that the error you mentioned when first updating is connected to this?

**Comment by 3ter** [comment]
@KajikiaAudax A workaround would be to replace the card templates for the note type manually. If you feel confident to do so, go ahead. Apart from that I hope @zjosua has a brilliant idea for tweaking the update mechanism :-).

**Comment by KajikiaAudax** [comment]
I just checked, yes, it's version 2.3.2. The error is still happening. I
have the latest version of Anki.

**Comment by KajikiaAudax** [comment]
Hey,

So I actually just bought a new laptop with my BidenBux. I downloaded Anki
on it and I got to my test multiple choice question... Well, it works fine
now! Interestingly, when I don't have the add-on installed in Anki (I don't
have the add-on on this laptop yet), the card works fine. I tested it with
a right answer and wrong answer and it puts up the correct %. This is on
the latest version of Anki with no plugins. The only plugins on my old Anki
were a background plugin I think, and your multiple choice plugin.

Best regards,
Phil

**Comment by 3ter** [comment]
That's very nice to hear :smiley_cat: 

And you are correct. The addon isn't needed for the functionality: the addon is a wrapper around the creation and updating of a note type containing the multiple choice magic. If the note type has been created you could go without the addon... if you don't care for updates that is :wink:

**Comment by 3ter** [comment]
Thanks to @zjosua all dependencies are now included in the release and the update worked fine for me.
This can be closed.

**Comment by Chichidimo** [comment]
Hi! It happens that I keep having this error. Any solution or suggestion?
