### ISSUE TITLE
The add-on "Multiple choice for anki" when installed shows "No configuration" and doesn't open.

### ISSUE THREAD

**Issue by dwij-dwij** [zjosua/anki-mc#47]
The "Multiple choice for Anki" Add-on is not opening and is showing in gray with "disabled" written on it. When double-clicked it pops up "Add-on has no configuration". Please help me fix this. Thanks.

**Comment by 3ter** [comment]
For me it helped to "Toggle Enabled" the addon and restart anki. Afterwards everything was fine.

**Comment by 3ter** [comment]
Most probably resolved by the latest updates.
