### ISSUE TITLE
Remove Colors

### ISSUE THREAD

**Issue by p1839251** [zjosua/anki-mc#53]
Hello,
I've looked through the tickets but I didn't find an answer to my question.
Can you tell me what these colors mean?
![confusion](https://user-images.githubusercontent.com/27902026/120907961-5e8a0700-c666-11eb-81da-ef2d2fc6d44b.jpg)
It's super confusing!
I selected 'flee' while 'free' was the right answer but 'fee' also had a different color, I really don't know why!

**Comment by p1839251** [comment]
I think I figured it out.
According to the program, **fee** was the only correct answer, as it was wrong and I didn't mark it as a good answer. ... Eh.
Sorry to say, but this isn't helpful at all in this case. Colors are more noticeable than radio buttons.
Is there a way to disable coloring? If not yet, please, make one because it's rather cumbersome to use it!

**Comment by p1839251** [comment]
I went through the issues and I noticed this feature is much more disliked than liked.
I agree, It's super distracting!
I'd like to know how I could disable it so the answers remain black and white.

**Comment by 3ter** [comment]
I actually do like the colors but if you want you can change those variables to false on the back template:
https://github.com/zjosua/anki-mc/blob/185f13413c7f84776c04b33e28fd4e2ff5690d7c/card/back.html#L23-L25

**Comment by p1839251** [comment]
thank you @3ter, it worked!

_A side question:
Could you tell me what to remove to get rid of the **Correct Answers x%**?
I don't think a wrong answer would be worth 33%_

**Comment by 3ter** [comment]
@p1839251 You could remove those three lines on the back card template
https://github.com/zjosua/anki-mc/blob/185f13413c7f84776c04b33e28fd4e2ff5690d7c/card/back.html#L15
https://github.com/zjosua/anki-mc/blob/185f13413c7f84776c04b33e28fd4e2ff5690d7c/card/back.html#L90-L91
