### ISSUE TITLE
Show Answers on AnkiDroid

### ISSUE THREAD

**Issue by p1839251** [zjosua/anki-mc#54]
I was trying to use this addon (_Single Choice_) on AnkiDroid but it behaves differently from the computer version.
It doesn't wait for the **SHOW ANSWER** button but as soon as I tap one of the radio buttons, the answer is displayed immediately.
What's even worse, if I don't tap precisely enough, none of the radio buttons will be selected and my answer is going to be wrong.

**Comment by 3ter** [comment]
I thought I've implemented the whole answer text to be clickable to make it harder to miss the response you wish to select.
Did this functionality stop working on AnkiDroid?

**Comment by p1839251** [comment]
I've just started using this addon. I don't know what it was like before.
This is how it's working on our device now.
Let me know if I could provide some helpful information!

**Comment by 3ter** [comment]
I've just confirmed that the labels are still clickable and single choice cards don't trigger the answer button to be pressed as expected. This was on Ankidroid `2.15.4`. I don't know in what way the mobile's OS could interfere with the functions used by AnkiDroid, but it worked that way on Samsung, Xiaomi and Pixel.

The "one-click-feature" reminds me of something that happened on iOS devices, there should be an issue somewhere about it. Perhaps it's a setting on Android as well influencing this?

If the labels are not clickable, then I'd say the template is not the one you can find [here](https://github.com/zjosua/anki-mc/tree/master/card). You could compare them in the note template editor (best done on Desktop) if that was the case.

As much as I'd want to help you more, the field of individual environments is too wide for both my current knowledge and my timetable I'm afraid. But if you've got further information, there should still be other devs around that might be able to help.

**Comment by p1839251** [comment]
I played around with it and I noticed that the choice has to be tapped super rapidly otherwise it triggers the answer button.
Labels are clickable.
If you tap the answer normally, it triggers the button. I never have to tap the Show Answer button.

**Comment by 3ter** [comment]
I suppose #83 solved this issue.
