### ISSUE TITLE
List the correct answers in preview instead of showing "x%" 

### ISSUE THREAD

**Issue by retiarylime** [zjosua/anki-mc#55]
It is hard for me to always study & review the card in order to revise the questions and answers because it will only display "x%" in preview mode.

**Comment by Erik262** [comment]
Just change the deck of these "anki-mc" cards then it starts working. Don't ask me why.

**Comment by RetiaryLime** [comment]
> Just change the deck of these "anki-mc" cards then it starts working. Don't ask me why.

What do you mean by changing anki-mc cards? Just change to new deck then it will show the correct answers even in preview mode?

**Comment by Erik262** [comment]
> > Just change the deck of these "anki-mc" cards then it starts working. Don't ask me why.
> 
> What do you mean by changing the deck of anki-mc cards?
> Just change to a new deck then it will show the correct answers even in preview mode?

Showing the correct answer in preview mode doesn't work for me either. Just move the cards you build with this addon to a completely different temporary deck and try to solve them. You will see they start working.

**Comment by 3ter** [comment]
This quick fix should be either in the Readme or the Wiki.
And the fact that previews cannot show the answer percentage as there's no answer saved in between unfortunately in preview mode.

@zjosua Do you have time to add this or shall I add another PR. My last one (refactoring only) got a bit stale by now, so that's why I bother you directly :-).

**Comment by 3ter** [comment]
@zjosua This can be closed as the _preview_ function from the "Browse" screen now works as expected.

By the way. I don't know if it is possible or even wanted but if you'd agree I'd like to apply for the needed roles to e.g. close already resolved or stale issues or PRs. Apparently my pedantry is a little more prominent than yours regarding the open issues whenever I stumble upon them 😉 .

**Comment by zjosua** [comment]
Thanks for the update @3ter.

> if you'd agree I'd like to apply for the needed roles to e.g. close already resolved or stale issues or PRs.

Yeah why not. As far as I know there is only full access (including PR merging etc), but that's fine.

As I stated in the bug report template, I'm not really motivated to put much effort into this addon as long as it works for me. But if you like to work on it feel free.

Are you on discord?
