### ISSUE TITLE
Enable/Disable shuffling?

### ISSUE THREAD

**Issue by K1NGM4RV** [zjosua/anki-mc#57]
Hello everyone! Is is possible to **turn off the shuffling** somehow? 
Also: is it possible to make the squares in front of the question bigger?

Thank you very much and best regards!
Marvin

**Comment by K1NGM4RV** [comment]
Just deleting the "onShuffle();" function from the front card will disable the shuffling!

**Comment by 3ter** [comment]
Closing as duplicate of #87 (which has more current information)
