### ISSUE TITLE
Answer text and numbers appear a few times when you roll the mouse

### ISSUE THREAD

**Issue by Radorion** [zjosua/anki-mc#59]
The only changes I made to the note were for aesthetics and to add another seven fields (twelve in total now), but sometimes, when you roll the mouse, it seems that field responses and numbers "leak" out of the card:

![image](https://user-images.githubusercontent.com/67805005/129114347-7ab9222e-330a-4a13-b0e5-62f1cbda9521.png)

**Comment by Radorion** [comment]
I don't understand about codar, but it might be something related to the line '<div class="hidden" id="user_answers">- - - -</div>'?

in:

`<div id="kard">
<div class="tags">#tags: {{Tags}}</div>
<div>{{#Pergunta}}<p>{{Pergunta}}</p>{{/Pergunta}}</div>

<table style="border: 1px solid black" id="qtable"></table>

<div class="hidden" id="Q_solutions">{{Answers}}</div>
<div class="hidden" id="user_answers">- - - -</div>
<div class="hidden" id="Card_Type">{{QType (0=kprim,1=mc,2=sc)}}</div>

<div class="hidden" id="Q_1">{{Q_1}}</div>
<div class="hidden" id="Q_2">{{Q_2}}</div>
<div class="hidden" id="Q_3">{{Q_3}}</div>
<div class="hidden" id="Q_4">{{Q_4}}</div>
<div class="hidden" id="Q_5">{{Q_5}}</div>
<div class="hidden" id="Q_6">{{Q_6}}</div>
<div class="hidden" id="Q_7">{{Q_7}}</div>
<div class="hidden" id="Q_8">{{Q_8}}</div>
<div class="hidden" id="Q_9">{{Q_9}}</div>
<div class="hidden" id="Q_10">{{Q_10}}</div>
<div class="hidden" id="Q_11">{{Q_11}}</div>
<div class="hidden" id="Q_12">{{Q_12}}</div>
</div>
`
The first 'kard' line is card style for a container, I don't know if it can influence hide.

**Comment by 3ter** [comment]
This most probably has been resolved with the new version of the addon.
