### ISSUE TITLE
Anki can´t display the cards I wrote with this flashcardtype. All I get is this errorcode

### ISSUE THREAD

**Issue by simon23421** [zjosua/anki-mc#61]
![Screenshot 2021-09-27 124225](https://user-images.githubusercontent.com/91466742/134893793-b0c038b4-2087-49a7-ae05-1c10b43392b4.png)

Not sure if I´m using it wrong or if it´s a bug

**Comment by 3ter** [comment]
This most probably has been resolved with the new version of the addon.
