### ISSUE TITLE
Errors with ⁨2.1.47

### ISSUE THREAD

**Issue by TrunkneFlut** [zjosua/anki-mc#63]
My wonderfully working Multiple Choice Addon suddenly doesn't work with Anki 2.1.47 anymore. It shows more answers than it should and does not correctly display the correct answers anymore
![image](https://user-images.githubusercontent.com/74065223/136157777-d2d8cad1-a585-4de5-821d-50cd41996a52.png)
![image](https://user-images.githubusercontent.com/74065223/136157845-18284496-2aa6-4e98-bb19-0db8a3be9308.png)

**Comment by 3ter** [comment]
I'm using 2.1.48 on both Windows and Linux and I haven't seen any change with any of the recent updates.

Maybe you changed your addons or note types in the process of updating?
