### ISSUE TITLE
Correct answer shown in red highlight (incorrect answer = 50%)

### ISSUE THREAD

**Issue by Kentaroni** [zjosua/anki-mc#66]
Good day! I'd just like to report this problem I've encountered with the add-on. Every time I answer the correct choice in the multiple choice question format, the correct answer and color coding (marked green at 100%) comes up; this works fine. [refer to image below]

![image](https://user-images.githubusercontent.com/92134609/136491505-2cf0ecd3-52b9-4e50-9c96-d56bcf1a1e83.png)

However, once I select the incorrect answer in the multiple choice question, the backside of the card shows the following:
1. Indicates the INCORRECT answer in a wrong color-code (can either be green or red)
2. Indicates the CORRECT answer in red BUT marks it as the correct answer (with a checked tickbox, meaning it is indeed correct)
3. Shows the score percentage as 50% since 2 choices is marked correct and the other 2 choices incorrect even when only 1 should be correct. [Please refer to the image below]

![image](https://user-images.githubusercontent.com/92134609/136491721-9860167d-cdd2-48b4-965d-961e7d1d17a3.png)

I have followed all the settings indicated in the add-on page. Specifically, for the sample question using multiple choice option above. The settings used for the sample question are as follows:

![image](https://user-images.githubusercontent.com/92134609/136491885-94899f4e-dd01-4f89-9b7f-f4c834ab900d.png)

Although I'm glad the correct answer is indicated by the ticked checkbox at the backside of the card, the red color and indication of "correct answers: 50%" is quite disorienting and confuses me at times since it would be more efficient to simply look for the single green option (to indicate it as correct) and see the "correct answers: 0%" to know that you've got the entire question wrong. I hope someone can help me on this! Overall, thank you for working on this add-on. Kudos!

Edit: some formatting errors

**Comment by zjosua** [comment]
The screenshots present the intended behaviour.

### Coloring
If you don't like it, you can change what is colored in the back template of the card.

To turn colors of completely, change the appropriate code (at the beginning of the second `<script>` tag) to:
```js
        var colorizeqtable = false;
        var colorizeatable = false;
        var colorizefalsefalse = false;
```

Maybe it makes more sense to have only the first table (the one you see on the front and back side) colored. For this the setting would be:
```js
        var colorizeqtable = true;
        var colorizeatable = false;
        var colorizefalsefalse = true;
```

The rationale behind coloring the non-ticked wrong answers green is that in the kprim, and to some extent in the multiple choice, question type, marking the wrong answers as wrong is a conscious action. If you don't want this, use `var colorizefalsefalse = false;`

### Percentage
Both @Kentaroni's second screenshot and the one posted by @senobe79 show the correct fraction of correct answers of 50%.
Ticking a wrong option counts as one wrong answer and not ticking the correct answer counts as one wrong answer. That leaves us with two out of four correct answers.

**Comment by SarahMK77** [comment]
Now i messed up all the code of AlllnOne (kprim, mc, sc) Is there any wat to paste again the original one ?!

**Comment by romerj0000** [comment]
I have the same issue on mine. It would mark the wrong answers green (sometimes all of the multiple choice would be marked green) and the correct answers red. Is anyone able to put in the code to fix this?

**Comment by 3ter** [comment]
> Now i messed up all the code of AlllnOne (kprim, mc, sc) Is there any wat to paste again the original one ?!

Yes, there are.

You can either 
1. rename the note type and then reinstall the addon
2. manually copy paste the code for [front](https://raw.githubusercontent.com/zjosua/anki-mc/master/card/front.html) and/or [back](https://raw.githubusercontent.com/zjosua/anki-mc/master/card/back.html)

**Comment by shahram7** [comment]
> The screenshots present the intended behaviour.
> 
> ### Coloring
> If you don't like it, you can change what is colored in the back template of the card.
> 
> To turn colors of completely, change the appropriate code (at the beginning of the second `<script>` tag) to:
> 
> ```js
>         var colorizeqtable = false;
>         var colorizeatable = false;
>         var colorizefalsefalse = false;
> ```
> 
> Maybe it makes more sense to have only the first table (the one you see on the front and back side) colored. For this the setting would be:
> 
> ```js
>         var colorizeqtable = true;
>         var colorizeatable = false;
>         var colorizefalsefalse = true;
> ```
> 
> The rationale behind coloring the non-ticked wrong answers green is that in the kprim, and to some extent in the multiple choice, question type, marking the wrong answers as wrong is a conscious action. If you don't want this, use `var colorizefalsefalse = false;`
> 
> ### Percentage
> Both @Kentaroni's second screenshot and the one posted by @senobe79 show the correct fraction of correct answers of 50%. Ticking a wrong option counts as one wrong answer and not ticking the correct answer counts as one wrong answer. That leaves us with two out of four correct answers.

Hi @zjosua,

how this behavior is intended?
I have the same issue with desktop version of Anki.
It shows by single choice the some random false answer (0) as true (1) and the true answer (1) as false (0)!
Regardless of setting the variables that you've named to true or false!

Best Regards

**Comment by zjosua** [comment]
@shahram7 this is not the same issue as OP had, but obviously a serious one regardless.
I can't really tell what went wrong from the screenshots. Could you export the note and email it to me?

**Comment by shahram7** [comment]
Hi @zjosua thank you for your respond. I thought I have the same problem as described in second post in this topic but you're right. Here is my Deck in a Zip file.
[Einbürgerungstest.zip](https://github.com/zjosua/anki-mc/files/7897179/Einburgerungstest.zip)

**Comment by buddabro** [comment]
Is there an update to your issue @shahram7 ? (meine farbgebung ist wie bei dir defekt)
I'd like to here from you soon!

**Comment by shahram7** [comment]
> Is there an update to your issue @shahram7 ? (meine farbgebung ist wie bei dir defekt) I'd like to here from you soon!

Hi,
No, unfortunately not.

**Comment by Schlauer-Hax** [comment]
I dont really see an issue with the coloring provided in your screenshot. However, if you would like to customize the coloring a bit more its possible with the code in my pullrequest i submitted #74. Maybe this could help solving your issue.

**Comment by Schlauer-Hax** [comment]
What i see is that the randomness of the answers is not correctly applied to the answerresults. This does not have anything todo with OPs issue and i think it would be better opening a new issue for that.

**Comment by zjosua** [comment]
@shahram7 I tested with you notes today. I can't reproduce your problem with the incorrect answers, which makes it near impossible for me to fix it. Therefore I will not put any more effort into the issue.

**Comment by luxurystorecc1** [comment]
High-Performance Socializing: The Intersection of Sport and StatusIntroduction: The Evolution of Social EtiquetteIn 2026, social etiquette has evolved to prioritize physical health and technical sophistication. Socializing now frequently takes place on the court, the course, or in high-tech urban environments. Navigating these spaces requires an "Active Status" wardrobe, anchored by the [Air Jordan 1 retro high OG sneakers](https://www.airjordan-1.com/).  Footwear as a Social SignifierYour choice of footwear is the first indicator of your lifestyle priorities. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) signify an appreciation for both athletic history and modern engineering. For collectors, [retro Jordan 1 limited editions](https://www.jordan1s.com/) serve as rare markers of cultural influence and refined taste.  The synergy between minimalist design and high-tech performance is found in the [Yeezy 350 boost performance sneakers](https://www.yeezyboost-350.com/collections/adidas-yeezy). This focus on lightweight, responsive design is mirrored in the widespread adoption of [comfortable Yeezy slides and foam runners](https://www.yeezyboost-350.com/) for relaxed, private social gatherings among the elite.  The Unified Dialect of Global Team GearSports gear has become a universal dialect that transcends local borders. Serious fans rely on the [official NFL shop online](https://www.nflshopofficialonline-store.com/) to secure gear that is both authentic and durable. The [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) has become a top choice for those who want to stand out within the global fanbase.  The cultural impact of the NBA is seen in the ubiquity of [NBA team hats and caps](https://www.cheapnfl-jerseys.com/collections/headwear-nba-headwear), while the growth of professional soccer is marked by the popularity of [MLS soccer jerseys for fans](https://www.soccerjerseysstore.com/collections/mls-jerseys). Hockey fans, too, maintain their standards by sourcing from the [NHL official site for jerseys](https://www.custombaseball-jerseys.com/).Performance Luxury: The Peter Millar StandardIn the exclusive world of "Performance Luxury," [Peter Millar women's golf outerwear](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear) offers a flawless combination of fashion and function. Designed to withstand the elements without restricting movement, these pieces are a staple of the modern social calendar. The broader [Peter Millar apparel collection](https://www.peter-milla.com/) remains the premier choice for sophisticated active wear.  Formal Traditions in the 2026 ContextEven the most traditional events now embrace modern inclusivity and comfort. For autumn milestones, [fall wedding guest dresses](https://www.swim-outlet.com/collections/wedding-fall-wedding-guest) allow guests to remain elegant regardless of weather changes. Bold choices like [elegant red evening dresses](https://www.swim-outlet.com/collections/dresses-red) continue to dominate galas for their timeless confidence.  Precision fit is now accessible to everyone through the [plus size formal dress collection](https://www.cheapdressesformal.com/), which mirrors the highest standards of luxury tailoring. Even private moments are elevated by [luxury sleepwear and intimates](https://www.cheapdressesformal.com/collections/clothing-sleepwear-sintimates) that utilize the finest silk and performance fabrics.  Conclusion: Integrity in Every SettingWhether you are on a world tour or attending a gala, the focus is on authenticity. From a [white formal gown](https://www.cheapdressesformal.com/collections/dresses-white) to professional athletic gear, choosing brands with integrity is the hallmark of the 2026 lifestyle.
