### ISSUE TITLE
Correct answers are shown in red and counted as wrong

### ISSUE THREAD

**Issue by Serkan1978** [zjosua/anki-mc#67]
It's my favorite addon :-)

But: My correctly selected answers are marked in red.
And are also counted as wrong.

This problem does not exist with the iPhone or Web-Version, only on my Mac-Version 2.1.35.

I've been dealing with it for days but can't find the fault.

Please excuse my english. Unfortunately, I have to work with the google translator.

<img width="161" alt="Bildschirmfoto 2021-11-06 um 19 20 06" src="https://user-images.githubusercontent.com/93838273/140619877-684e406c-2120-462b-a96f-8386991c59f6.png">

**Comment by zjosua** [comment]
Unfortunately I can't test on Mac OS.
Are you sure that this is only reproducible on  Mac?

**Comment by KALKI-the-avataar** [comment]
@zjosua also same problem in windows and it also not autograding the question

**Comment by zjosua** [comment]
@Gaaruda could you provide a screenshot?
