### ISSUE TITLE
Wrong highlighted color for multiple choice 

### ISSUE THREAD

**Issue by starslxd** [zjosua/anki-mc#71]
I have set 4 answer for multiple choice question. When I click wrong answer and click show answer button, 2 answer become red and other 2 answer become green, Does it expected result?

My Fields
![Fields](https://user-images.githubusercontent.com/8794859/148568798-88cd5323-7f7b-4c4a-84b6-d3ffdbad82bf.png)

My Result:
![Result](https://user-images.githubusercontent.com/8794859/148568793-c2da89d9-02c1-4002-ae79-c07a0ae83376.png)

**Comment by zjosua** [comment]
Yes, this is intended.
2 is red because you selected it but I should not be selected. 3 is red because it should be selected, but wasn't.
1 and 4 are green because you did not select them, which is correct.

**Comment by starslxd** [comment]
Understood your concept completely, thanks for your clarification!
