### ISSUE TITLE
Answers not in random order

### ISSUE THREAD

**Issue by fredrikcoulter** [zjosua/anki-mc#73]
I would like the answers to not be in random order.  This allows for some answers to be something like Both A & B.

On the Anki page for the addin, there's a detailed explanation of how to change the code so that the answers are no longer randomized.  I found the template.py file and made the edits to the source code using WordPad.  However, most of the way through the explanation, it says:

In the style tab, add this CSS:

.nightMode .correct1 {
color: ghostwhite;
background-color: lime;
box-shadow: 0 0 0 3px darkgreen inset;
}

.correct1 {
color: ghostwhite;
background-color: #009900;
box-shadow: 0 0 0 3px darkgreen inset;
}
.errado {
color: red;
}
.errada {
color: ghostwhite;
background-color: OrangeRed;
box-shadow: 0 0 0 3px darkred inset
}

.certo {
color: darkgreen;
}

The problem is that I have no idea where the style tab is to make this edit.

How can I change the addin so that it no longer randomizes the answers?  I may need a bit more handholding.

**Comment by 3ter** [comment]
Manage Note Types → AllInOne → Cards...
![image](https://user-images.githubusercontent.com/11499929/151125150-da288031-35c9-4fab-ad24-c567da1d5a1e.png)
Then you'll find the stylesheet to edit it to your liking.

**Comment by zjosua** [comment]
To disable randomizing of the answers, change `onShuffle();` in the Front Template of the AllInOne card to `// onShuffle();`.
