### ISSUE TITLE
Multiple choice add-on not working on mobile app

### ISSUE THREAD

**Issue by Anna34BanAnna** [zjosua/anki-mc#76]
I've searched for answers, and have followed every bit of advice all to no avail.  Is there any way to get the multiple choice questions to work on the app for ios?  The app continuously marks questions as incorrect, nor can I multi-select answers to some questions.  Any guidance you could provide is much appreciated.

**Comment by bullboa** [comment]
Late comment but there is an old discussion here: https://github.com/zjosua/anki-mc/issues/56
Unfortunately the suggestion there doesn't work for me.

**Comment by 3ter** [comment]
I suppose #83 solved this issue.
