### ISSUE TITLE
Coloring is confusing

### ISSUE THREAD

**Issue by Erik262** [zjosua/anki-mc#79]
![Screen Shot 2022-04-16 at 09 58 12](https://user-images.githubusercontent.com/11977647/163667177-a2e54848-238d-45bd-bccf-862b191f230d.png)

Coloring is very very confusing. Here an example

**Comment by zjosua** [comment]
You can customise the coloring in the `const options` block near the top of the back template of the "AllInOne" card type.

**Comment by Matina42** [comment]
zjosua,

I'm having the same issue. I want the **correct answers highlighted in green** and **wrong answers highlighted in red**, as I suppose this feature is intended. I'm using Anki 2.1.49 on Windows 10.

If that isn't possible, could you please let me know how to remove the highlighting altogether? That would be preferable to having it highlighted in the wrong colour.

Best regards,
Matina

**Comment by zjosua** [comment]
@Matina42 set the coloring options in the back template to
```js
                colors: { // Defines which class should be set
                    wrongwrong: 'wrong', // Should be wrong and got marked as wrong
                    correctcorrect: 'correct', // Should be correct and got marked as correct
                    wrongcorrect: 'wrong', // Should be wrong but got marked as correct
                    correctwrong: 'correct', // Should be correct but got marked as wrong
                    eithernone: "wrong" // Kprim was marked neither correct nor wrong
                }
```

**Comment by KingdomB** [comment]
This is a copy of the adjustment that I made per the instructions above and I am still getting this error:
const options = {
            qtable: {
                visible: true,
                colorize: false,
                colors: { // Defines which class should be set
                    wrongwrong: 'wrong', // Should be wrong and got marked as wrong
                    correctcorrect: 'correct', // Should be correct and got marked as correct
                    wrongcorrect: 'wrong', // Should be wrong but got marked as correct
                    correctwrong: 'correct', // Should be correct but got marked as wrong
                    eithernone: "wrong" // True/False was marked neither correct nor wrong
                }
            },
            atable: {
                visible: true,
                colorize: true,
                colors: { // Defines which class should be set
                    wrongwrong: 'wrong', // Should be wrong and got marked as wrong
                    correctcorrect: 'correct', // Should be correct and got marked as correct
                    wrongcorrect: 'wrong', // Should be wrong but got marked as correct
                    correctwrong: 'correct', // Should be correct but got marked as wrong
                    eithernone: "wrong" // True/False was marked neither correct nor wrong
                }
            }
        }

**Comment by Matina42** [comment]
Thanks heaps, it’s working perfectly now!

Matina

 

Von: Yoshi ***@***.***> 
Gesendet: Sonntag, 8. Mai 2022 16:53
An: zjosua/anki-mc ***@***.***>
Cc: Matina42 ***@***.***>; Mention ***@***.***>
Betreff: Re: [zjosua/anki-mc] Coloring is confusing (Issue #79)

 

@Matina42 <https://github.com/Matina42>  set the coloring options in the back template to

                colors: { // Defines which class should be set
                    wrongwrong: 'wrong', // Should be wrong and got marked as wrong
                    correctcorrect: 'correct', // Should be correct and got marked as correct
                    wrongcorrect: 'wrong', // Should be wrong but got marked as correct
                    correctwrong: 'correct', // Should be correct but got marked as wrong
                    eithernone: "wrong" // Kprim was marked neither correct nor wrong
                }

**Comment by Borjatgalan** [comment]
The bad issue I see with this fix is that the choices won't be shuffled. :( 
I would like to have both features.

**Comment by 3ter** [comment]
> The bad issue I see with this fix is that the choices won't be shuffled. :( I would like to have both features.

What are you referring to? The last two versions had nothing to do with shuffling. Did you by chance comment in the wrong issue?

**Comment by Borjatgalan** [comment]
> > The bad issue I see with this fix is that the choices won't be shuffled. :( I would like to have both features.
> 
> What are you referring to? The last two versions had nothing to do with shuffling. Did you by chance comment in the wrong issue?

Sorry my bad, shuffling choices is working perfectly. Cheers.
