### ISSUE TITLE
Filling the Field "QType"

### ISSUE THREAD

**Issue by hugomarins** [zjosua/anki-mc#8]
What do **kprim**, **mc** and **sc** stand for? There's nothing about it in the "usage" section. Could you please let me know?

**Comment by zjosua** [comment]
It lets you select the question type: Kprim, Multiple Choice or Single Choice ([Screenshots](https://github.com/zjosua/anki-mc/#screenshots) show how they look).
Thanks for the notice, I've updated the documentation.
