### ISSUE TITLE
More than five answer options

### ISSUE THREAD

**Issue by Innoberger** [zjosua/anki-mc#81]
**If you are about to request a different color coding, consider coding it yourself and submitting it as a pull request. Most likely I will not reply to requests for different color coding if they are submitted as an issue.**

**Is your feature request related to a problem? Please describe.**
Not a problem, it's a "nice-to-have" feature.

**Describe the solution you'd like**
I need to get more answer options than five.

**Describe alternatives you've considered**
I tried coding it myself, but I failed. I also tried to edit the config files, but that didn't help either.

**Additional context**
---

**Comment by zjosua** [comment]
Gisela has already done this:
https://ankiweb.net/shared/info/1573325751
https://github.com/giselaortt/anki-multiple-choice-with-12-options

See [this diff](https://github.com/zjosua/anki-mc/compare/master...giselaortt:master) for an idea how to code it yourself with the desired amount of options.
