### ISSUE TITLE
AnkiDroid is closing by itself whenever I choose the "AllInOne (kprim, mc, sc)" note type.

### ISSUE THREAD

**Issue by EVR1997** [zjosua/anki-mc#86]
AnkiDroid is closing by itself whenever I choose the "AllInOne (kprim, mc, sc)" note type.

**Comment by 3ter** [comment]
Please copy the debug message from the error displayed when the application crashes.

**Comment by 3ter** [comment]
Couldn't reproduce with the version from Ankiweb.
