### ISSUE TITLE
Is there a way to turn off answers RANDOMization?

### ISSUE THREAD

**Issue by awsfreakpl** [zjosua/anki-mc#87]
First of all - great add-on - it helped me a lot - great job. Question: I am trying to figure out if there is a way to turn off answers randomization. I have a scenario where the order of answers is essential. Could you please advise? Thanks.

**Comment by n30s4m** [comment]
There is no such field, there is only an add-on that has up to 12 questions. What chaos!
In the one with 5 questions, the option to edit the colors appears, but in the one with 12 questions, it does not appear. What chaos!

**Comment by ileandromendes** [comment]
Hello! Please, could you add some printscreens regarding how to disable shuffling?I’ve tried add the comment on code but doesn’t work.
Thx!

**Comment by zcccccc1** [comment]
On the latest addon version, change the front template code

```
let shuffledQuestionTableHtmlLinesToSolution = getShuffledQuestionTableHtmlLinesToSolution(
            questionTableHtmlLinesToSolution, type, OPTIONS['maxQuestionsToShow']);
```

to

```
let shuffledQuestionTableHtmlLinesToSolution = questionTableHtmlLinesToSolution;
```
