### ISSUE TITLE
mc solutions wrong 

### ISSUE THREAD

**Issue by ksaadDE** [zjosua/anki-mc#88]
Regarding the MC stuff:
1. correct questions are marked as wrong ( or not recognized at all )
2. checkboxes in the second view ( the results view ) are wrong

idc about your coloring but idk how you use it, if it does not work properly. I have seen a PR but it is not merged for about nine months

**Comment by 3ter** [comment]
@ksaadDE Thank you for using the addon. Please use the bug report template and check my comment on said PR.
