### ISSUE TITLE
Update AnkiWeb documentation

### ISSUE THREAD

**Issue by zjosua** [zjosua/anki-mc#91]
The added config options from Version 2.7.0 are not documented on AnkiWeb yet.

**Comment by 3ter** [comment]
I haven't really thought on the release process on AnkiWeb yet :see_no_evil: .

I'm probably going for using this [Markdown Plugin for vscode](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) to generate the HTML and then add the section `Support` from the current `ankiweb.html`.
