### ISSUE TITLE
SC question not working

### ISSUE THREAD

**Issue by alexotay** [zjosua/anki-mc#98]
Single choice question formatting is wrong:
![image](https://user-images.githubusercontent.com/121296861/209337955-694a4925-5bd9-48d3-a392-53c77fe063b9.png)
Answers not shown, only "correct answers: X%"
![image](https://user-images.githubusercontent.com/121296861/209338000-5f0ac1c6-5b1d-4e3f-bab0-86db1eff2505.png)

**Comment by 3ter** [comment]
I can't reproduce this using a pristine installation of the addon (use `anki -b path/to/temp/folder`). Both the formatting and the answer percentage are shown correctly.

Do you need further assistance with debugging the issue?

**Comment by 3ter** [comment]
No answer from author.
