### ISSUE TITLE
Is it possible to show only 5 random answers from 10 possible answers ?

### ISSUE THREAD

**Issue by MajinTORTUE** [zjosua/anki-mc#99]
Hi i'm a french med student and in my university we have a huge database of questions for our final exams. So basically I've just found your add-on on ANKIweb annd i added the posibility to have 10 answers, but for the exam of my university, we will have like 10 answers ( 5 goods and 5 wrongs  ) and the application will pick randomly 5 answers then show it to us.

Is it possible to add this kind of feature for your add on ? 

With your answer you will massively help a lot of people

Best regards

**Comment by 3ter** [comment]
I'm not sure if that's exactly what you've asked for so before opening a pull request I'd like to ask your opinion on the following changes I've made.

I suppose you've created a note type that's a clone of the one created by this multiple choice addon and then added fields up to `Q_10`.
So for this note type please replace the code for the front card with the one from my fork of this repo:
https://raw.githubusercontent.com/3ter/anki-mc/add-option-to-restrict-number-of-answers-shown/src/multiple_choice/card/front.html

**Comment by 3ter** [comment]
@MajinTORTUE Is this still relevant?

**Comment by MajinTORTUE** [comment]
Yeah it is ! Thank you so much !

Envoyé de mon mobile
Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
